# Generated by Django 5.0.3 on 2024-04-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
