# Generated by Django 5.0.3 on 2024-04-08 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_product_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimages",
            old_name="images",
            new_name="image",
        ),
    ]
