# Generated by Django 5.0.3 on 2024-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_product_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("disabled", "Disabled"),
                    ("in_review", "In Review"),
                    ("published", "Published"),
                    ("in_stock", "In Stock"),
                ],
                default="in_review",
                max_length=10,
            ),
        ),
    ]
