# Generated by Django 5.0.3 on 2024-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_product_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("black", "Black"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="Size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
