# Generated by Django 5.0.3 on 2024-04-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_product_color_product_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="Color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="Size",
        ),
    ]
